class Conversation < ApplicationRecord
  DEFAULT_TITLE_FORMAT = "%Y-%m-%d %H:%M:%S.%6N"
  # matches titles generated by start! (DEFAULT_TITLE_FORMAT), i.e. conversations the user never renamed
  DEFAULT_TITLE_PATTERN = /\A\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{6}\z/
  UNNAMED_DELETION_CONFIRMATION = "confirm"

  has_many :conversation_messages, dependent: :destroy

  validates :title, presence: true, uniqueness: true

  scope :ordered, -> { order(updated_at: :desc) }

  def self.start!
    create!(title: Time.current.strftime(DEFAULT_TITLE_FORMAT))
  end

  # based on the saved title, so a rename that failed validation doesn't change what deletion asks for
  def named?
    !title_in_database.to_s.match?(DEFAULT_TITLE_PATTERN)
  end

  # what the user must type to confirm deleting this conversation
  def deletion_confirmation
    named? ? title_in_database : UNNAMED_DELETION_CONFIRMATION
  end
end
